### ISSUE TITLE
HJÄLP MIG - Style module 1 & 3

### ISSUE THREAD

**Issue by Fagerdahl** [El-Duckster/EscapeRoom-grupp2#13]
Jag har en fundering, ang css. jag vill styla modal 1 och 3 som jag strukturerat upp nu. 
Jag skapande en css- och scss fil i Elenas mappar. Men när jag skulle sass compila så funkar det inte och jag vet inte vad som felar. 
Bifogar skärmdumpar på det jag gjort i hopp om att få hjälp att förstå hur jag kan komma vidare.  Jag har alltså inte sparat något av det konstiga jag skrev in i Elenas json fil, utan jag har bara försökt att få min scss att kompileras till sass, men vet inte om jag refererar rätt. Felmeddelanden kommer upp på löpande band. Bör jag skriva enbart css  för att vinna tid ? 

Tack på förhand, ni e grymma 

![Image](https://github.com/user-attachments/assets/5f419629-c792-40cd-a0d2-bfd78f088c48)
![Image](https://github.com/user-attachments/assets/6f0f1f3d-afe9-4a66-898a-2e31d8656606)

**Comment by El-Duckster** [comment]
Skulle du kunna pusha dina senaste ändringar till GitHub? Jag ser ingen kod i modal.scss. För att allt ska funka behöver lägga till lägga till **@use 'modal.scss'** i main.scss och sedan köra **npm run watch-css** i terminalen. på bilden ovan ser jag att du bara hade kört npm run. 

Hör gärna av dig om problemet kvarstår

kul med att ha konversationen här , eller hur :))

**Comment by Fagerdahl** [comment]
Jag har gjort styling i min modal.scss fil, men jag kommer inte att köra sass- så imorgon flyttar jag över dem i css. Det blir för rörigt när jag inte får det att funka helt 100. Jag har funderat över min modal nummer 1... Den ska ju poppa upp från din html basically, så för att ha din hemsida i bakgrunden så behöver jag använda iframes. Jag blandade sedan in att börja skapa funktion för bokningsknappen, men det kom jag överens med Linnea om att inte göra eftersom att vi inte vill peta på era andras moment.  Nu har jag rört till det lite känner jag och vet inte hur jag ska komma vidare. Första modalen ser somewhat ut som den ska, men den är inte helt klar. Tacksam för alla råd och hjälp jag kan få!

**Comment by Fagerdahl** [comment]
sass compilation OK. All is good in the hood :-)
