### ISSUE TITLE
Bug/Card container button

### ISSUE THREAD

**Issue by Kirill9m** [El-Duckster/EscapeRoom-grupp2#56]
![Screenshot_20241116_125833_Kiwi Browser](https://github.com/user-attachments/assets/67757e29-ea32-4b4e-baab-35132a40d418)

A minor bug: depending on the containers text size, the button's position adjusts relative to the text.

![Screenshot_20241116_125846_Kiwi Browser](https://github.com/user-attachments/assets/c871e9d5-495e-41b4-a6b8-5c1b12e22ff0)

I can suggest setting a minimum width for the container. Do someone have any other interesting ideas?

**Comment by Fagerdahl** [comment]
Hmm.. I am thinking of a flex display and align items to flex-end, but not sure. 
What about getting the container position relative, so the buttons can get "absoluted"? 
Worth a try maybe :-) You are doing a great job Kirill !

**Comment by El-Duckster** [comment]
Just to make sure I’m on the same page :) are you referring to adjusting the minimum height? Maybe you could try tweaking the button properties, like right: 0 and bottom: 0. I’d recommend holding off on the styling for now and focusing on the key adjustments to the core functionality. I’ve reviewed the PR for the Challenge class, and there are a few changes we’ll need to make before :)

**Comment by El-Duckster** [comment]
fixed it :)
