### ISSUE TITLE
Fix/pseudo element type

### ISSUE THREAD

**Issue by Kirill9m** [El-Duckster/EscapeRoom-grupp2#57]
The pseudo-element that provides the task name is applied to all tasks by default. 
![Screenshot_20241116_144420_Kiwi Browser](https://github.com/user-attachments/assets/7b8c2372-8baf-41a9-8b26-4d2308ff5db5)

It is  also difficult to modify it via JavaScript.
![Screenshot_20241116_144407_Kiwi Browser](https://github.com/user-attachments/assets/dd07ff15-ce70-44da-816b-d968eacc16ed)

Any suggestions? Which direction should I look into?

**Comment by Kirill9m** [comment]
https://github.com/El-Duckster/EscapeRoom-grupp2/pull/3#discussion_r1844983913

**Comment by El-Duckster** [comment]
> Temporary solution to display the type element.
> 
> [#3 (comment)](https://github.com/El-Duckster/EscapeRoom-grupp2/pull/3#discussion_r1844983913)

Jag har svarat på PR :)
